language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# install: python setup.py install
env:
  - DJANGO=1.4.1
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install mysql-python --use-mirrors
  # - pip install -q -e . --use-mirrors


before_script:
  - mysql -e 'create database seal;'
  - mysql -u root < ci_scripts/ci_dbuser.sql
  - python seal/manage.py syncdb < admin-root-user-data.txt
    
test:
    adapter: mysql2
    database: seal
    username: seal
    password: $3alSEAL
    encoding: utf8

# command to run tests, e.g. python setup.py test
script:  python seal/manage.py test

notifications:
  email:
    recipients:
      tanomarti05@gmail.com
      aniballovaglio@yahoo.com.ar
    on_success: change
    on_failure: always
