from seal.model.course import Course
from seal.model.student import Student
from seal.model.teacher import Teacher
from seal.model.practice import Practice
from seal.model.delivery import Delivery
from seal.model.correction import Correction
from seal.model.suscription import Suscription
from seal.model.automatic_correction import AutomaticCorrection
from seal.model.script import Script
from seal.model.mail import Mail
from seal.model.practice_file import PracticeFile
from seal.model.shift import Shift